- apps/extension/contents/chatgpt-microphone.tsx
- apps/extension/contents/microphone.tsx
I accidentally had pushed the Chrome extension to the web store before it was ready and wanted to get this fix out as soon as possible!
For now, I'm disabling injecting the microphone button in all websites EXCEPT `chatgpt.com` and `claude.ai`. This will fix many of the errors people are having as it was unintentional functionality.
Please let me know if people are interested in restoring the button on websites other than `chatgpt.com` and `claude.ai`. I will create adapters for those desired websites.
closes
- Messing up UI for Bing #121
- "Oops, an error occurred!" When uploading an image on chatGPT #120
- Whispering not working on Paymo app field #123
- Update Breaks Google sheets #118
> fix: disable microphone button, show only on chatgpt and anthropic website

- apps/app/src-tauri/Cargo.toml
- apps/app/src-tauri/src/main.rs
This should ideally fix builds in actions, and continues to solve #19
> fix: conditionally include accessibility-sys and core-foundation-sys only if target os is macos

- apps/app/package.json
- apps/app/src-tauri/Cargo.lock
- apps/app/src-tauri/Cargo.toml
- apps/app/src-tauri/tauri.conf.json
- apps/app/src/lib/services/MediaRecorderServiceWebLive.ts
- apps/app/src/lib/stores/recorder.svelte.ts
- apps/app/src/lib/stores/settings.svelte.ts
- apps/app/src/lib/utils/createPersistedState.svelte.ts
- apps/app/src/routes/(app)/+page.svelte
- apps/app/src/routes/(config)/+layout.svelte
- apps/app/src/routes/+layout.svelte
- apps/extension/lib/services/extension-storage.ts
- apps/extension/package.json
- package.json
When the microphone start recording, we skips the enumeration of devices and only do so if the selected device no longer exists. This greatly speeds up startup time of recording, since the old method would always enumerate devices even when not necessary.
closes #117
> feat: faster enumeration of recorder devices

- apps/app/src-tauri/tauri.conf.json
Running `cargo clean` fixed my ealier issues with global shortcut not being triggered when in background. Closes #137
> feat: enable window in background

- apps/app/src/routes/(config)/settings/+page.svelte
Some users have had issues with getting API keys to work. I have added billing instructions using the link
https://platform.openai.com/settings/organization/billing/overview
in the settings page.
> feat: add billing instructions in settings page

- apps/app/src/lib/services/ClipboardService.ts
- apps/app/src/lib/services/ClipboardServiceDesktopLive.ts
- apps/app/src/lib/services/ClipboardServiceExtensionLive.ts.ts
- apps/app/src/lib/services/ClipboardServiceWebLive.ts
- apps/app/src/lib/stores/recordings.svelte.ts
- apps/extension/background/messages/external/setClipboardText.ts
- apps/extension/popup.tsx
> fix: move macos permissions prompt from copy text to write text

- apps/app/src/lib/services/TranscriptionServiceGroqLive.ts
> fix: trim beginning and end whitespace in post processing from groq

- apps/app/src/lib/stores/recordings.svelte.ts
- apps/app/src/routes/(config)/settings/+layout.svelte
- apps/app/src/routes/(config)/settings/replacements/+page.svelte
- packages/shared/src/index.ts
Add Word Replacement Feature for Text Transcription
This PR introduces a new replacement tab that allows users to define custom word replacements during text transcription. Users can specify pairs of original words and their desired replacements, which are then automatically applied as a post processing step after transcription.
Key benefits:
- Saves time by allowing users to define replacements once and apply them consistently across all transcriptions
- Improves accuracy by ensuring consistent naming/terminology throughout documents
- Particularly useful for:
- Standardizing product/company names
- Replacing acronyms with full names
- Localizing specific terms
- Maintaining consistent terminology in technical documentation
- Anonymizing sensitive information
> feat: add replacements tab

- apps/app/src-tauri/tauri.conf.json
- Fix macOS microphone permissions not being requested in desktop app
- Add Linux and Windows platform configurations
- Enable audio support for Linux builds
The Tauri desktop app wasn't showing up in macOS microphone permissions because the `tauri.conf.json` was missing the macOS entitlements configuration. This prevented the app from requesting microphone access.
1. **macOS Fix**: Added `entitlements.plist` configuration to properly request microphone permissions
2. **Linux Support**: Enabled `bundleMediaFramework` for AppImage to include GStreamer for audio recording
3. **Windows Support**: Added WebView2 bootstrapper configuration
4. **App Description**: Added short description for app stores
> fix(tauri): add macOS microphone permissions and cross-platform bundle config

- README.md
updated "M1/M2/M3" to "M1/M2/M3/M4"
> docs: add missing mentions of M4 Mac in README.md

- apps/app/src-tauri/Cargo.toml
- Add Rust compiler optimization profiles to reduce Tauri app binary size
- Following the official Tauri v2 size optimization guide
- Added `[profile.dev]` section with incremental compilation for faster development builds
- Added `[profile.release]` section with multiple size optimizations:
- `codegen-units = 1`: Better LLVM optimization
- `lto = true`: Link-time optimizations
- `opt-level = "s"`: Prioritize small binary size
- `panic = "abort"`: Remove panic handlers for smaller size
- `strip = true`: Remove debug symbols
- Tauri Size Optimization Guide: https://v2.tauri.app/concept/size/
- Fixes #574
> feat: optimize Tauri binary size with Rust compiler flags

- apps/whispering/src/lib/components/NotificationLog.svelte
> fix: #601 - set data-sonner-toast to relative when descendant of popover-content

- apps/whispering/src/routes/+layout/AppShell.svelte
notification history button was pushed below bottom of screen. Moved min-height: 100vh from div to body and set body to grid with rows '1fr auto'
> removed min-height from div, set body to grid '1fr auto'

- apps/whispering/src/lib/components/settings/README.md
- apps/whispering/src/lib/components/settings/selectors/DeviceSelector.svelte
- apps/whispering/src/lib/query/recorder.ts
- apps/whispering/src/lib/query/settings.ts
- apps/whispering/src/lib/services/index.ts
- apps/whispering/src/lib/services/recorder/desktop.ts
- apps/whispering/src/lib/services/recorder/index.ts
- apps/whispering/src/lib/services/recorder/web.ts
- apps/whispering/src/lib/settings/settings.ts
- apps/whispering/src/routes/(config)/+layout.svelte
- apps/whispering/src/routes/(config)/settings/recording/+page.svelte
- apps/whispering/src/routes/(config)/settings/recording/SelectRecordingDevice.svelte
- apps/whispering/src/routes/+page.svelte
This PR adds the ability for users to select between native (Rust/CPAL) and browser (MediaRecorder API) recording backends in the desktop app. This provides a workaround when users encounter issues with either backend.
- Added `recording.backend` setting with options 'native' (default) and 'browser'
- Setting only appears in desktop app where both backends are available
- Exported `NativeRecorderServiceLive` and `BrowserRecorderServiceLive` as separate static services
- Services maintain closure lifetimes as required
- Query layer dynamically selects appropriate service based on user preference
- Refactored `DeviceSelector` component to use single `mode` prop ('manual' or 'vad')
- Removed redundant `strategy` prop - backend is now derived internally from:
- Recording mode (VAD always uses …
> feat(recording): allow users to select between native and browser recording backends

- apps/whispering/src/lib/components/NotificationLog.svelte
- Before this change, the `class` defined here (in the snippet) was being overwritten by the props being passed in.
- This ensures the button truly has fixed positioning as intended by the classes.
- **Note:** the `right-4` is also honored now, moving the button from the left to right corner. (The button will be covered by any toasts, making it inaccessible.)
- **Note:** the `z-50` is also honored, making the button appear above the modal overlay; however this is only visual. (Clicking the button will not activate the notifications log.)
- This PR fixes the same bug as: https://github.com/epicenter-so/epicenter/pull/673
**Notifications button is not hidden at xxs breakpoint.**
**Notifications button is not fixed; must scroll to bottom to find**
**All classes honored, now: `fixed bottom-4 …
> fix(whispering): ensure notifications button has classes applied.

- apps/whispering/src/routes/+page.svelte
**This PR updates the integration link behavior:**
- Desktop app (Tauri runtime): No integration links are shown.
- Website: Only the desktop app link is shown (removed the Chrome extension link).
- Tooltip: Updated to "Get Whispering for desktop" for clearer guidance.
**Changes**
- Removed conditional rendering of the Chrome extension link.
- Updated WhisperingButton tooltip content.
- Simplified logic: window.__TAURI_INTERNALS__ hides content in app; website only shows desktop app link.
> show only desktop app link on website, hide in desktop

- apps/whispering/src/routes/(config)/settings/+page.svelte
- fixes #704 
- The copy and paste switches had pretty confusing labels. This PR addresses that and makes the labels more descriptive to what they are actually do.
> Make copy and paste lables in settings more descriptive

- apps/whispering/src/lib/components/NavItems.svelte
**This PR marks the start of improving navigation overall in the codebase** 
- Right now, our navigation is kind of all over the place and has some issues with UX flow, see example ->  #710
- It's not that we have bad navigation, but it feels a bit unintuitive
- This PR highlights navigation items making it easier for the user to know where they currently are
> Before
> After
---
> Add active state highlighting to navigation items

- docs/articles/git-worktrees-inside-your-repository.md
- docs/articles/how-conductor-uses-git-worktrees.md
Add two comprehensive articles explaining Git worktree organization patterns.
The first article explains how Conductor uses Git worktrees with a brilliant organizational approach, stacking all worktrees inside a dedicated `.conductor/` directory within the repository. This keeps everything neatly organized instead of scattered across the file system.
The second article is a deep dive into organizing Git worktrees inside your repository rather than creating sibling directories. It addresses the common problem of cluttered code folders and shows how to keep all worktrees contained within the project directory using patterns like `.worktrees/`.
Both articles emphasize the key insight that Git doesn't care where worktrees live, so you can organize them however makes sense for your workflow. …
> docs(articles): add git worktree organization guides

- apps/whispering/src/lib/components/settings/WhisperModelSelector.svelte
This was preventing models from downloading correctly.
> add missing / to `getModelsDirectory()`

- apps/whispering/src/lib/stores/settings.svelte.ts
- apps/whispering/src/routes/+layout/register-commands.ts
Replace single resetShortcuts(type) method with dedicated resetLocalShortcuts() and resetGlobalShortcuts() methods. Eliminates switch statement and provides cleaner abstraction with method-specific behavior.
> refactor(settings): replace resetShortcuts switch with dedicated methods

- apps/whispering/src/lib/constants/transcription/transcription-services.ts
- apps/whispering/src/lib/query/transcription.ts
- apps/whispering/src/lib/services/analytics/types.ts
- apps/whispering/src/lib/services/ffmpeg/desktop.ts
- apps/whispering/src/lib/services/ffmpeg/types.ts
- apps/whispering/src/lib/services/ffmpeg/web.ts
- apps/whispering/src/lib/services/recorder/ffmpeg.ts
- apps/whispering/src/lib/settings/settings.ts
- apps/whispering/src/routes/(config)/settings/recording/+page.svelte
- apps/whispering/src/routes/(config)/settings/recording/FfmpegCommandBuilder.svelte
- apps/whispering/src/routes/(config)/settings/transcription/+page.svelte
- apps/whispering/src/routes/+layout/check-ffmpeg.ts
This adds optional audio compression before transcription to reduce file sizes and API costs while maintaining transcription quality. Users can compress audio using FFmpeg before sending to transcription services, with comprehensive preset options and custom configuration support.
The implementation integrates seamlessly into the existing transcription workflow with automatic fallback to original audio if compression fails. Compression typically reduces file sizes by ~6x (e.g., 1.5MB WAV to 240KB Opus) while preserving speech quality for accurate transcription.
The feature includes four compression presets optimized for different use cases: Recommended (Opus 32kbps), Smallest (Opus 16kbps), Compatible (MP3), and High Quality (MP3 64kbps). Users can also specify custom FFmpeg compression …
> feat(transcription): add audio compression before transcription

- apps/whispering/src/lib/components/settings/CompressionBody.svelte
- apps/whispering/src/lib/components/settings/index.ts
- apps/whispering/src/lib/components/settings/selectors/CompressionSelector.svelte
- apps/whispering/src/lib/components/settings/selectors/ManualDeviceSelector.svelte
- apps/whispering/src/lib/components/settings/selectors/RecordingModeSelector.svelte
- apps/whispering/src/lib/components/settings/selectors/VadDeviceSelector.svelte
- apps/whispering/src/lib/query/commands.ts
- apps/whispering/src/lib/query/recorder.ts
- apps/whispering/src/lib/query/transcription.ts
- apps/whispering/src/lib/query/vad-recorder.ts
- apps/whispering/src/lib/services/recorder/ffmpeg.ts
- apps/whispering/src/lib/settings/settings.ts
- apps/whispering/src/lib/stores/settings.svelte.ts
- apps/whispering/src/routes/(config)/+layout.svelte
- apps/whispering/src/routes/(config)/settings/recording/+page.svelte
- apps/whispering/src/routes/(config)/settings/recording/FfmpegCommandBuilder.svelte
- apps/whispering/src/routes/(config)/settings/recording/ManualSelectRecordingDevice.svelte
- apps/whispering/src/routes/(config)/settings/recording/SelectRecordingDevice.svelte
- apps/whispering/src/routes/(config)/settings/recording/VadSelectRecordingDevice.svelte
- apps/whispering/src/routes/(config)/settings/shortcuts/global/+page.svelte
- apps/whispering/src/routes/(config)/settings/shortcuts/local/+page.svelte
- apps/whispering/src/routes/(config)/settings/transcription/+page.svelte
- apps/whispering/src/routes/+layout/AppShell.svelte
- apps/whispering/src/routes/+layout/check-ffmpeg.ts
- apps/whispering/src/routes/+page.svelte
- docs/articles/svelte-function-bindings-readonly-stores.md
This refactors the device selection architecture from method-specific to mode-specific storage, significantly simplifying both the codebase and user experience. Previously, each recording method (CPAL, FFmpeg, Navigator) maintained its own device ID, creating unnecessary complexity and potential confusion for users switching between methods.
The new architecture uses mode-specific device storage: `recording.manual.selectedDeviceId` for manual recording and `recording.vad.selectedDeviceId` for voice-activated recording. This change makes the device selection more intuitive since users think in terms of recording modes (manual vs VAD) rather than technical implementation methods.
Additionally, this removes the compression UI components (`CompressionSelector`, `CompressionBody`) that were …
> refactor: simplify device selection architecture

- apps/whispering/src-tauri/Cargo.lock
- apps/whispering/src-tauri/Cargo.toml
- apps/whispering/src-tauri/src/recorder/commands.rs
- apps/whispering/src-tauri/src/whisper_cpp/mod.rs
- apps/whispering/src/lib/query/transcription.ts
- apps/whispering/src/lib/services/transcription/whispercpp.ts
- apps/whispering/src/lib/settings/settings.ts
- apps/whispering/src/routes/(config)/settings/transcription/+page.svelte
This PR fixes build errors related to whisper-rs GPU acceleration features on macOS.
The build was failing with undefined symbol errors (`___isPlatformVersionAtLeast`) when Metal was enabled. Additionally, the `whisper-cpp-log` feature doesn't exist in whisper-rs v0.15.0.
1. Remove non-existent `whisper-cpp-log` feature from all whisper-rs dependencies
2. Disable Metal feature on macOS due to linking issues, keeping only CoreML
3. Add broader GPU support for other platforms (Vulkan, HipBLAS)
- macOS: Uses CoreML for Apple Silicon Neural Engine acceleration
- Windows: Uses CUDA for NVIDIA GPUs and Vulkan for AMD/Intel GPUs  
- Linux: Uses CUDA, Vulkan, and HipBLAS for maximum GPU compatibility
The build now completes successfully while still maintaining GPU acceleration capabilities across …
> fix(whisper): resolve GPU acceleration build issues

- apps/whispering/src/lib/components/settings/CompressionBody.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/AnthropicApiKeyInput.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/DeepgramApiKeyInput.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/ElevenLabsApiKeyInput.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/GoogleApiKeyInput.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/GroqApiKeyInput.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/OpenAiApiKeyInput.svelte
- apps/whispering/src/lib/components/settings/api-key-inputs/OpenRouterApiKeyInput.svelte
- apps/whispering/src/routes/(config)/recordings/+page.svelte
- apps/whispering/src/routes/(config)/settings/transcription/+page.svelte
- apps/whispering/src/routes/(config)/transformations/+page.svelte
Converts oninput handlers to more idiomatic binding patterns:
- Settings inputs: Use function bindings with getter/setter pattern
- Simple state: Use bind:value for direct binding
Benefits:
- Eliminates boilerplate event handling code
- Provides better type safety and IDE support
- Consistent with Svelte 5 binding patterns
- More declarative approach to two-way binding
Changes:
- All API key inputs: value + oninput → bind:value with function bindings
- Transcription settings: speaches URL, model ID, temperature, prompt
- Compression settings: custom options input
- Filter inputs: globalFilter and filterQuery use simple bind:value
Builds on #752
> refactor: migrate oninput handlers to function bindings and bind:value

- apps/whispering/src/routes/(config)/recordings/row-actions/EditRecordingModal.svelte
This fixes the audio player rerendering
every time users type in the edit
recording modal input fields. Previously,
typing in the title, subtitle, or other
text fields would cause the audio player
to reload and reset its playback
position, creating a poor user
experience.
The issue occurred because the audio
player's `src` was derived from
`workingCopy.blob`, but `workingCopy`
gets updated on every keystroke. Since
the audio blob itself never changes
during editing (users are only modifying
metadata), the audio player was
unnecessarily rerendering.
before: 
https://github.com/user-attachments/assets/2ef9e4b7-7e2a-4df2-9550-50a765106207
after: 
https://github.com/user-attachments/assets/cd0cdcb9-9da5-45d1-89eb-5d6fc8492e61
> fix(EditRecordingModal): prevent audio rerendered

- apps/whispering/src/lib/query/transcription.ts
- apps/whispering/src/routes/(config)/settings/recording/+page.svelte
- apps/whispering/src/routes/(config)/settings/transcription/+page.svelte
- apps/whispering/src/routes/+layout/AppShell.svelte
- apps/whispering/src/routes/+layout/check-ffmpeg.ts
- docs/architecture/dependency-injection-async-sync-pattern.md
- packages/config/eslint.ts
This PR refactors the FFmpeg compatibility checking logic to use dependency injection, solving the async/sync impedance mismatch between RPC calls and Svelte templates.
- `requiresFFmpegForLocalTranscription` → `hasLocalTranscriptionCompatibilityIssue`
- Better reflects the dual-purpose nature (FFmpeg OR settings change can resolve)
- `checkFfmpegRecordingMethodCompatibility()` - Validates FFmpeg when selected as recording method
- `checkLocalTranscriptionCompatibility()` - Checks local transcription compatibility issues
- `checkCompressionRecommendation()` - Suggests compression for cloud transcription
- `hasLocalTranscriptionCompatibilityIssue` now accepts `isFFmpegInstalled` as a parameter
- Function remains synchronous for use in Svelte templates
- Callers fetch FFmpeg status in their …
> refactor: improve FFmpeg compatibility checks with dependency injection

- packages/config/eslint.ts
This PR removes the ESLint perfectionist plugin and its associated sorting rules from our base configuration.
The perfectionist plugin was enforcing automatic sorting of imports and objects throughout the codebase. While code organization is important, enforcing strict alphabetical/natural sorting can be counterproductive in several scenarios:
1. Semantic grouping is often more valuable than alphabetical sorting - Related imports or object properties are better kept together based on their logical relationship rather than alphabetical order. For example, grouping all UI component imports together, then utility imports, then types.
2. Unnecessary code churn - The sorting rules create noise in diffs when developers need to add new imports or properties, making PR reviews harder and git …
> chore: remove eslint perfectionist plugin and sorting rules

- bun.lock
- packages/ui/package.json
Updated vaul-svelte: the older version must not be compatible with the other UI packages/code.
Fixes: https://github.com/epicenter-md/epicenter/issues/658
> Fix: modal trigger not rendered on mobile breakpoints.

- apps/whispering/src-tauri/capabilities/default.json
- apps/whispering/src-tauri/src/recorder/recorder.rs
Fixes Linux audio recording issues with a targeted sample format filtering approach that resolves the core compatibility problem without adding external dependencies.
This addresses the same Linux audio recording failures described in #697, which affects Ubuntu 24.04+ and other PipeWire-based distributions. While #698 and #729 propose comprehensive solutions using GStreamer, this PR takes a more targeted approach by fixing the underlying sample format compatibility issue within the existing CPAL architecture.
The core issue wasn't a fundamental CPAL/PipeWire incompatibility, but rather a sample format mismatch. Linux audio devices (particularly with ALSA/PipeWire) often default to 8-bit integer (I8) sample format, which the recorder didn't support. This caused "Unsupported sample format: …
> fix(recording): resolve Linux audio recording failures

- apps/whispering/src/routes/+error.svelte
I realized that we didn't have a dedicated error page so therefore I added a very simple version of the page. 
> Before 
> After
> Add simple error page for 404 and other errors

- apps/whispering/src-tauri/src/transcription/mod.rs
This change adds proper inference parameters to the Parakeet transcription engine.
Previously, we were passing `None` for the inference parameters. This PR configures `ParakeetInferenceParams` with `TimestampGranularity::Segment` to follow recommended usage patterns and potentially improve performance.
- Import `ParakeetInferenceParams` and `TimestampGranularity` from transcribe-rs
- Configure inference params with segment-level timestamp granularity
- Pass configured params instead of `None` to `transcribe_samples()`
This is a minimal change that should be tested with existing Parakeet transcription workflows to verify any performance improvements.
> fix(parakeet): add inference parameters for transcription

- apps/whispering/src/routes/(config)/settings/api-keys/+page.svelte
Adding the  `<DeepgramApiKeyInput />` in the `settings/api-keys` page since we already have code to support it.
> feat(api-keys): add deepgram APIkeyInput component in settings

- apps/whispering/src/routes/+layout.svelte
- apps/whispering/svelte.config.js
This PR adds [Svelte Inspector](https://www.npmjs.com/package/@sveltejs/vite-plugin-svelte-inspector)
- For new devs: helps discover relevant source files.
- For experienced devs: convenient way to open Svelte files in editor.
- Activated via toggle button or CMD-SHIFT/CTRL-SHIFT (+ click)
Summary of changes:
- Enable Svelte inspector for click-to-edit-source functionality
- Configure bottom-center positioning to avoid UI conflicts with devtools and toasts
- Support toggle button (always visible) and keyboard shortcuts (Cmd+Shift, Alt+X)
> feat(dev): add Svelte inspector in bottom-center.

- apps/whispering/src/lib/query/recordings.ts
This fixes the issue where the recordings page doesn't update when a recording is created while already on the recordings page.
Previously, when creating a recording from the recordings page itself, the new recording wouldn't appear in the table until the page was manually refreshed or navigated away and back. The issue occurred because while the mutation updated the cache via setQueryData, it didn't invalidate the query, which is necessary to trigger re-renders for active query consumers.
This change adds queryClient.invalidateQueries for recordingKeys.all to the createRecording mutation. The mutation now follows the standard TanStack Query pattern: use setQueryData for optimistic updates (immediate UI feedback), then use invalidateQueries to mark the query as stale and trigger a …
> fix: invalidate all recordings query after creating a new recording

- apps/whispering/src-tauri/capabilities/default.json
This change adds explicit Linux-specific file system paths to the Tauri capabilities configuration to resolve file access permission errors on Linux systems.
On Linux, Tauri's file system security model requires explicit permission grants for app data directories, even when wildcard permissions are configured. This was causing "forbidden path" errors when users tried to download models or save recordings.
The update adds three Linux-specific paths to the `fs:scope` permission in `capabilities/default.json`:
- `$APPDATA/**` for cross-platform app data compatibility
- `$HOME/.local/share/**` for general Linux app data directory access  
- `$HOME/.local/share/com.bradenwong.whispering/**` for explicit Whispering app directory access
This addresses file system permission issues reported by …
> feat(linux): add explicit file system permissions for app data directory

- apps/whispering/src/routes/(config)/settings/recording/+page.svelte
- docs/specs/20251006T181526 linux-vad-limitation.md
This change adds a prominent warning when users select VAD mode on Linux platforms, where the Navigator API is not fully supported in Tauri.
When VAD mode is selected on Linux, users now see a red error alert explaining that device enumeration and recording will fail, with a link to issue #839 for more details. On other platforms, the existing blue informational alert continues to work as before.
The implementation keeps VAD mode visible in the recording mode dropdown on all platforms to maintain UI consistency. Linux users receive immediate clear feedback when they select VAD mode, explaining why it won't work on their platform and directing them to use Manual recording mode instead.
The technical limitation stems from VAD mode requiring the browser's Navigator API …
> feat(recording): add Linux VAD limitation warning

- apps/whispering/src/lib/components/settings/CompressionBody.svelte
This change adds an amber warning alert to the compression settings that appears when FFmpeg is not installed. Previously, the compression checkbox was simply disabled without a clear explanation of why or how to enable it.
The warning alert appears at the bottom of the CompressionBody component and includes an AlertTriangle icon for visual emphasis, clear messaging that FFmpeg is required for audio compression, and a direct link to the /install-ffmpeg page for easy installation.
This alert displays in both locations where compression settings appear: the compression popover in the app header and the transcription settings page. Users now have a clear path forward when they encounter the disabled compression checkbox.
> feat(CompressionBody): add ffmpeg installation warning alert
