- apps/app/src/lib/components/CancelOrEndRecordingSessionButton.svelte
- apps/app/src/routes/(app)/+page.svelte
- apps/app/src/routes/(config)/+layout.svelte
- apps/app/src/routes/(config)/recordings/+page.svelte
Place these buttons in the UI in both the main page and the layout in settings
> feat: standardize toggle, cancel, and destroy stream buttons

- apps/app/src/lib/components/CancelOrEndRecordingSessionButton.svelte
- apps/app/src/lib/services/MediaRecorderService.svelte.ts
- apps/app/src/lib/stores/recorder.svelte.ts
- apps/app/src/lib/stores/settings.svelte.ts
- apps/app/src/routes/(config)/settings/+page.svelte
- apps/extension/options.tsx
> fix: enter api key in extension settings page

- apps/app/src/lib/services/MediaRecorderService.svelte.ts
- apps/app/src/lib/stores/recorder.svelte.ts
> major fix: undo navigator settings causing broken safari audio

- apps/app/src/lib/services/RegisterShortcutsService.ts
- apps/app/src/lib/services/RegisterShortcutsServiceDesktopLive.ts
- apps/app/src/lib/services/RegisterShortcutsServiceWebLive.ts
- apps/app/src/lib/stores/recorder.svelte.ts
- apps/app/src/lib/stores/settings.svelte.ts
- apps/app/src/lib/utils/createPersistedState.svelte.ts
- apps/app/src/routes/(config)/settings/+page.svelte
- apps/extension/background/messages/contents/getSettings.ts
- packages/shared/src/index.ts
> feat: enable changing bitrate in settings

- apps/app/src/lib/stores/recordings.svelte.ts
> fix: don't always annoyingly reprompt for accessibility

- apps/extension/contents/poe.tsx
Closes [FEATURE REQUEST]: Integration of Whispering browser extension with Poe.com #193
> feat: add poe support

- apps/extension/contents/chatgpt-microphone.tsx
- apps/extension/contents/claude.tsx
- apps/extension/contents/microphone.tsx
> fix: inconsistencies with claude rendering and fixed white screen of death

- .github/workflows/publish-tauri-releases.yml
I finally got it to work, 1 year later, after following https://tauri.app/v1/guides/distribution/sign-macos/ one more time!
It didn't work last time, so I hope it does now 🤞
> feat: include code signing

- apps/app/src/lib/components/CancelOrEndRecordingSessionButton.svelte
- apps/app/src/lib/services/MediaRecorderService.svelte.ts
- apps/app/src/lib/stores/recorder.svelte.ts
Used to close #185 , which eventually addresses #175
> feat: auto timeout mediaStream

- .github/workflows/publish-tauri-releases.yml
This reverts commit 79cb73335098844b025cd21c7f9b4029369fe101.
Closes #221
> hotfix: undo code signing

- .github/workflows/publish-tauri-releases.yml
- apps/app/src-tauri/entitlements.plist
> fix: restore notarization

- apps/app/src/routes/(config)/recordings/+page.svelte
> feat: update table layout

- apps/app/package.json
- pnpm-lock.yaml
> chore: remove svelte french toast

- apps/app/src/lib/services/ClipboardServiceDesktopLive.ts
- apps/app/src/lib/stores/recordings.svelte.ts
> refactor: macos specific clipboard things to clipboard service

- apps/app/src/lib/services/DownloadService.ts
- apps/app/src/lib/services/DownloadServiceDesktopLive.ts
- apps/app/src/lib/services/DownloadServiceWebLive.ts
- apps/app/src/lib/stores/recordings.svelte.ts
> feat: download service that infers file extension from blob

- apps/app/src/lib/stores/recordings.svelte.ts
> fix: conditionally inject openai or groq provider

- apps/app/src/routes/(config)/settings/SettingsLabelInput.svelte
- apps/app/src/routes/(config)/settings/transcription/+page.svelte
> fix: restore password field for api keys

- apps/app/src/routes/(config)/recordings/+page.svelte
> feat: use handlebars instead for templating, default include timestamp in front of bulk copies

- packages/shared/src/services/TranscriptionService.ts
> feat: faster-whisper-server actually has cors support, restore to browser platform as well

- .github/workflows/add-sponsors-to-readme.yml
> fix: readme updating

- biome.json
- package.json
- pnpm-lock.yaml
> chore: add biome

- apps/app/src/lib/services/ClipboardServiceDesktopLive.ts
- apps/app/src/lib/services/SetTrayIconServiceDesktopLive.ts
- apps/app/src/lib/services/renderErrorAsToast.ts
- apps/extension/background/messages/whispering-extension/writeTextToCursor.ts
- packages/shared/src/index.ts
> refactor: use isWarning instead of passing variant into WhisperingError

- apps/app/src/lib/stores/recorder.svelte.ts
- apps/app/src/routes/+layout.svelte
- apps/extension/background/messages/extension/createNotification.ts
- apps/extension/background/messages/extension/ping.ts
- apps/extension/contents/whispering.ts
- apps/extension/lib/extension.ts
- apps/extension/popup.tsx
> hotfix: prevent hangs in sendToBackgroundViaRelay when extension is not installed

- apps/app/src/lib/query/singletons/shortcutsRegister.ts
- apps/app/src/routes/(config)/settings/recording/+page.svelte
- apps/app/src/routes/(config)/settings/shortcuts/keyboard-shortcut-recorder/GlobalShortcutTable.svelte
- apps/app/src/routes/(config)/settings/shortcuts/keyboard-shortcut-recorder/KeyboardShortcutRecorder.svelte
- apps/app/src/routes/(config)/settings/shortcuts/keyboard-shortcut-recorder/LocalShortcutTable.svelte
You can now assign push to talk shortcut in /settings/shortcuts!
> feat: push to talk shortcut

- apps/app/src/lib/toast.ts
- apps/app/src/routes/+layout/AppShell.svelte
Move action button to bottom of toasts like so:
> feat: better toast styling, move action button to bottom of toast

- apps/app/src/lib/commands.ts
- apps/app/src/lib/components/NavItems.svelte
- apps/app/src/lib/query/_queries/cpalRecorder.ts
- apps/app/src/lib/query/_queries/manualRecorder.ts
- apps/app/src/lib/query/_queries/vadRecorder.ts
- apps/app/src/lib/services/local-shortcut-manager.ts
- apps/app/src/lib/stores/settings.svelte.ts
- apps/app/src/lib/utils/createPersistedState.svelte.ts
- apps/app/src/routes/(config)/+layout.svelte
- apps/app/src/routes/(config)/recordings/+page.svelte
- apps/app/src/routes/(config)/transformations/+page.svelte
- specs/20250125T123456-consolidated-settings-migration.md
- specs/20250624T065427 refactor-error-config.md
- Replaced direct button elements with a dynamic dropdown menu for collapsed navigation on mobile devices.
- Introduced a new `navItems` array to manage navigation links and actions, improving maintainability and scalability.
- Updated layout to conditionally render the dropdown or standard navigation based on screen size.
> feat: navigation items use a dropdown menu for mobile view

- apps/app/src/lib/components/settings/selectors/TranscriptionSelector.svelte
> feat(ui): overhaul TranscriptionSelector

- apps/app/src/lib/commands.ts
- apps/app/src/lib/query/commands.ts
Exposed separate commands for starting and stopping manual recording, simplified implementation with refactoring
This addresses the request in #67 for different hotkeys for starting and stopping speech recognition. The exposed commands allow for more flexible control through keyboard shortcuts or external tools like AutoHotkey.
> feat: expose start and stop manual recording commands

- docs/articles/blog-post-self-contained-components.md
update self-contained-components.md at line:
- 18
-  66
- 117
> docs: update blog post self-contained-components

- README.md
Added Rust and Cargo installation instructions to prerequisites.
> Update prerequisites in README.md

- apps/whispering/src/lib/constants/icons/README.md
- Add concise README for icons directory describing purpose and contents
- Note sources for SVGs (Simple Icons and SVGL)
> docs: README for icons directory

- README.md
> Docs: remove temporary dev update from README.md.

- apps/whispering/src/routes/(config)/recordings/+page.svelte
- apps/whispering/src/routes/(config)/transformations/+page.svelte
> fix: css typo from scroll-m=20 to scroll-m-20
